### ISSUE TITLE
[list-separator] TypeError when reading 'split'

### ISSUE THREAD

**Issue by C-Ezra-M** [mavoweb/plugins#117]
Somehow, this happened unexpectedly in a Mavo app I'm making. I used the codebase as if mavoweb/mavo#1025 was already merged, as Netlify is deploying it for use with a `<script>` tag.
```
mavo-list-separator.js:22 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at node-render-start (mavo-list-separator.js:22:70)
    at deps.js:2:1
    at Array.forEach (<anonymous>)
    at n.run (deps.js:2:1)
    at Collection.render (node.js:302:1)
    at Collection.<anonymous> (group.js:181:1)
    at Group.propagate (node.js:246:1)
    at Group.dataRender (group.js:162:1)
    at Group.render (node.js:344:1)
    at Mavo.render (mavo.js:356:1)
```

**Comment by DmitrySharabin** [comment]
Hey there,

Thank you for reporting the bug. I’m planning to give it a closer look ASAP. Is there a chance you could share a piece of your code causing the bug, e.g., on Codepen? It would help us to narrow down the issue tremendously.

**Comment by C-Ezra-M** [comment]
Somehow, that issue was caused by having incomplete initial data (i.e. all but one property were excluded). And unfortunately, I can't easily reproduce this bug since it's inconsistent. However, it does sometimes cause multiline input to be pasted twice.
